### ISSUE TITLE
NullPointerException when searching for a particular set of terms

### ISSUE THREAD

**Issue by marco-brandizi** [Rothamsted/knetbuilder#42]
Happening with babvs73, wheat instance, with our without a gene list. From the code, should be about concepts without a name attached, will fix it with a check/default.

```log
20210421-14:37:25.398 [http-nio-8080-exec-10] ANALYTICS analytics-log - {datasource=wheatknet-beta, host=babvs73.rothamsted.ac.uk, keywords="growth" OR "cell division" OR "cell proliferation" OR "inflorescence" OR "carbohydrate metabolism" OR "photosynthesis" OR "grain number" OR "grain weight" OR "grain hardness" OR "spikelets" OR "tillers" OR "vernalization" OR "vernalisation" OR "Plant photoperiod response", list=["TraesCS3A02G245000","TraesCS3B02G275000","TraesCS3D02G246500","TraesCS3D02G401400","TraesCS3B02G439900","TraesCS3A02G406200","TraesCS4D02G040400","TraesCS4A02G271000","TraesCS4A02G466700","TraesCS4B02G043100","TraesCS2A02G116900","TraesCS2B02G136100","TraesCS2D02G118200","TraesCS2A02G081900","TraesCSU02G196100","TraesCS2D02G079600","TraesCS5D02G245300","TraesCS5A02G238400","TraesCS5B02G236900"], mode=genome, port=9100, qtl=[]}
20210421-14:37:25.717 [http-nio-8080-exec-10] INFO  OndexLocalDataSource - Number of user provided genes: 19
20210421-14:37:25.717 [http-nio-8080-exec-10] INFO  OndexLocalDataSource - Search mode: rres.knetminer.datasource.api.GenomeResponse
20210421-14:37:26.360 [http-nio-8080-exec-10] INFO  SearchService - searchLucene(), keywords: ""growth" OR "cell division" OR "cell proliferation" OR "inflorescence" OR "carbohydrate metabolism" OR "photosynthesis" OR "grain number" OR "grain weight" OR "grain hardness" OR "spikelets" OR "tillers" OR "vernalization" OR "vernalisation" OR "Plant photoperiod response"", returning 11512 total hits
20210421-14:37:26.360 [http-nio-8080-exec-10] INFO  Hits - Matching Lucene concepts: 11512
20210421-14:37:26.806 [http-nio-8080-exec-10] INFO  Hits - Matching unique genes: 79324
20210421-14:37:26.806 [http-nio-8080-exec-10] INFO  OndexLocalDataSource - Genome or QTL response...
20210421-14:37:26.806 [http-nio-8080-exec-10] INFO  SearchService - Total hits from lucene: 11512
20210421-14:37:38.115 [http-nio-8080-exec-10] INFO  OndexLocalDataSource - Number of genes: 79324
20210421-14:37:39.507 [http-nio-8080-exec-10] INFO  OndexLocalDataSource - Using user gene list, genes: 19
20210421-14:37:39.507 [http-nio-8080-exec-10] INFO  ExportService - Genomaps: generating XML...
20210421-14:37:39.508 [http-nio-8080-exec-10] INFO  SearchService - QTL search query: +ConceptClass:Trait +(ConceptName:growth ConceptName:"cell division" ConceptName:"cell proliferation" ConceptName:inflorescence ConceptName:"carbohydrate metabolism" ConceptName:photosynthesis ConceptName:"grain number" ConceptName:"grain weight" ConceptName:"grain hardness" ConceptName:spikelets ConceptName:tillers ConceptName:vernalization ConceptName:vernalisation ConceptName:"plant photoperiod response")
20210421-14:37:39.514 [http-nio-8080-exec-10] ERROR KnetminerExceptionHandler - Returning exception from web request processing, HTTP status: '500 INTERNAL_SERVER_ERROR'
java.lang.RuntimeException: Application error while running genome: null
	at rres.knetminer.datasource.server.KnetminerServer._handle(KnetminerServer.java:388) ~[classes/:?]
	at rres.knetminer.datasource.server.KnetminerServer.handle(KnetminerServer.java:328) ~[classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197) ~[spring-web-5.3.1.jar:5.3.1]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141) ~[spring-web-5.3.1.jar:5.3.1]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.3.1.jar:5.3.1]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:893) ~[spring-webmvc-5.3.1.jar:5.3.1]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:807) ~[spring-webmvc-5.3.1.jar:5.3.1]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.1.jar:5.3.1]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1061) [spring-webmvc-5.3.1.jar:5.3.1]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:961) [spring-webmvc-5.3.1.jar:5.3.1]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) [spring-webmvc-5.3.1.jar:5.3.1]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) [spring-webmvc-5.3.1.jar:5.3.1]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652) [servlet-api.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) [spring-webmvc-5.3.1.jar:5.3.1]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) [servlet-api.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) [catalina.jar:9.0.41]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.41]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) [tomcat-websocket.jar:9.0.41]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.41]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.41]
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) [log4j-web-2.14.0.jar:2.14.0]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) [catalina.jar:9.0.41]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) [catalina.jar:9.0.41]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) [catalina.jar:9.0.41]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) [catalina.jar:9.0.41]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) [catalina.jar:9.0.41]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) [catalina.jar:9.0.41]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [catalina.jar:9.0.41]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690) [catalina.jar:9.0.41]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) [catalina.jar:9.0.41]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [catalina.jar:9.0.41]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374) [tomcat-coyote.jar:9.0.41]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) [tomcat-coyote.jar:9.0.41]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:888) [tomcat-coyote.jar:9.0.41]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1597) [tomcat-coyote.jar:9.0.41]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-coyote.jar:9.0.41]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:9.0.41]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at rres.knetminer.datasource.server.KnetminerServer._handle(KnetminerServer.java:375) ~[classes/:?]
	... 43 more
Caused by: java.lang.NullPointerException
	at rres.knetminer.datasource.ondexlocal.service.SearchService.searchQTLsForTrait(SearchService.java:393) ~[server-datasource-ondexlocal-5.0-SNAPSHOT.jar:?]
	at rres.knetminer.datasource.ondexlocal.service.SearchService.searchQTLs(SearchService.java:457) ~[server-datasource-ondexlocal-5.0-SNAPSHOT.jar:?]
	at rres.knetminer.datasource.ondexlocal.service.ExportService.exportGenomapXML(ExportService.java:551) ~[server-datasource-ondexlocal-5.0-SNAPSHOT.jar:?]
	at rres.knetminer.datasource.ondexlocal.OndexLocalDataSource._keyword(OndexLocalDataSource.java:240) ~[server-datasource-ondexlocal-5.0-SNAPSHOT.jar:?]
	at rres.knetminer.datasource.ondexlocal.OndexLocalDataSource.genome(OndexLocalDataSource.java:164) ~[server-datasource-ondexlocal-5.0-SNAPSHOT.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at rres.knetminer.datasource.server.KnetminerServer._handle(KnetminerServer.java:375) ~[classes/:?]
	... 43 more
```

**Comment by marco-brandizi** [comment]
Wrongly put here, it's actually a ticket for knetminer.
